server:
  port: 9088


#服务名称
spring:
  application:
    name: cloud-mysql-service  #入住进eureka时的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver            # mysql驱动包 com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shangmifirstweek?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

# 配置mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名