swagger: "2.0"
info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification
schemes:
  - https

host: localhost
basePath: /users
paths:
  /user:
    get:
      summary: 简单说明
      description: 详细说明
      parameters:
        - name: username
          in: query
          description: 用户名
          type: string
          pattern: "[a-z0-9A-Z]{8,64}"            #用户名长度介于8~64，由字母和数字组成
          minLength: 8                            #最小长度
          maxLength: 64                           #最大长度
        - name: pageSize
          in: query
          description: 每页的大小
          type: integer
          format: int32           #integer分为int32和int64
          minimum: 0              #最小值
          exclusiveMinimum: true  #是否可以等于最小值。   true：表示必须大于最小值。   false：表示可以等于最小值
          maximum: 100
          exclusiveMaximum: false
          multipleOf: 10         #表示必须是10的整数倍
          default: 1             #默认值
